### ISSUE TITLE
Missing unit tests

### ISSUE THREAD

**Issue by kellieotto** [kdpeterson51/mbir#2]
This is detailed feedback for your JOSS review openjournals/joss-reviews#746.

R packages should have a tests/ directory containing unit tests. Hadley Wickham’s R packages book has a whole chapter explaining how to do this.

Better yet, you could set up a continuous integration system with Travis CI and add a badge to your README.md that shows that your package passes all of the tests.

**Comment by kdpeterson51** [comment]
@kellieotto, thank you for your patience. mbir has successfully [![Build Status](https://travis-ci.org/kdpeterson51/mbir.svg?branch=master)](https://travis-ci.org/kdpeterson51/mbir) with Travis CI. 

Please inform me if there is anything you may need from me.

Again, thank you.

**Comment by kellieotto** [comment]
Great, Travis CI looks like it's working!

Your package still needs comprehensive unit tests for its functions. I'll point you to some resources on how to do this. Please let me know if you need more information.

http://r-pkgs.had.co.nz/tests.html
https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf
https://testthat.r-lib.org/index.html

**Comment by kdpeterson51** [comment]
@kellieotto @leeper, a [tests](https://github.com/kdpeterson51/mbir/tree/master/mbir/tests) folder has now been updated.

**Comment by kellieotto** [comment]
Good start. I hate to nitpick but these unit tests aren't comprehensive. They check that your functions are internally coherent with each other, but only for one example each. I'd like to see tests for more (ideally all) of your functions, more than one test for each, and testing that the outputs of your functions match some external reference (i.e. not just that they match each other).

**Comment by leeper** [comment]
I agree.

**Comment by kellieotto** [comment]
I see that you've added some new tests. These look great. Again, I'd like to see tests for more (ideally all) of your functions and testing that the outputs of your functions match some external reference.

**Comment by leeper** [comment]
Just to keep track, I see tests of the following:

- [x] aipe_smd
- [x] boot_test
- [x] corr
- [ ] corr_diff
- [x] corr_test
- [ ] es_convert
- [ ] odds
- [ ] prop
- [x] smd
- [x] smd_test
- [x] ss_corr
- [x] ss_odds
- [x] ss_smd
- [ ] swc_ind

It would be good to see tests of the remaining functions.

**Comment by leeper** [comment]
@kdpeterson51 Just a ping. It would be great to see this final issue of testing resolved, as we're very close to being able to accept this.

**Comment by kellieotto** [comment]
Looks like the functions with unchecked boxes can be checked off now.
