### ISSUE TITLE
Missing version on Github

### ISSUE THREAD

**Issue by kellieotto** [kdpeterson51/mbir#3]
This is detailed feedback for your JOSS review openjournals/joss-reviews#746.

You should create a version of your package in the Github repository that matches the version number on CRAN. Versioning is tracked here: https://github.com/kdpeterson51/mbir/releases

**Comment by kdpeterson51** [comment]
Thanks for your help, @kellieotto. 

The most current version on CRAN (1.3.1) has been uploaded to Github.
